# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-27 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20171127_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='history',
            field=models.CharField(default='no history available', max_length=500),
            preserve_default=False,
        ),
    ]
