# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-29 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_band_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='mp3song',
            field=models.FileField(default=0, upload_to=b''),
            preserve_default=False,
        ),
    ]
