# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-11 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
